### ISSUE TITLE
Disallow nesting complex selectors

### ISSUE THREAD

**Issue by proycon** [annotation/stam#10]
In the current specification complex selections (multi selectors, composite
selectors and directional selectors) can be nested at will, including multiple
nested layers. This allows the user to build a whole tree of selectors but
creates the problem that the semantic interpretation of such a tree is not
clearly defined.

I want to prevent this issue from arising by simply forbidding nesting of
complex selectors. If users want to build a tree-like structure then the proper
way to do so in in STAM is to create annotations that refer to other
annotations, not through selectors (annotations carry labels, ids, etc..
selectors do not). This fits better with our 'everything is an annotation'
principle. It also simplifies implementing selectors.

**Comment by dirkroorda** [comment]
I second this.
