### ISSUE TITLE
Expand STAM Query language with the ability to ADD and DELETE items

### ISSUE THREAD

**Issue by proycon** [annotation/stam#22]
Right now STAMQL is read-only, add `ADD` and `DELETE` statements to make the query language able to manipulate data.

Note: an `EDIT` statement is less likely to be implemented due to the immutable nature of annotations in STAM.

**Comment by dirkroorda** [comment]
Power!

**Comment by proycon** [comment]
Implemented, still needs to be documented though (see also #23)
