### ISSUE TITLE
why must a private identifier start with _?

### ISSUE THREAD

**Issue by eduarddrenth** [annotation/stam#4]
The second is a private identifier, an internal numeric identifier (starting with an underscore)....

I know this is sometimes used as coding convention (i.e. in environments that do not support scoping), but I am not a fan.

**Comment by proycon** [comment]
At this point it's just a convention used in the specification to communicate that certain properties are internal/private. Implementations may choose their own naming. I guess the text may also be a bit confusing here, I didn't mean to imply that the numeric identifier itself starts with an underscore!
